---
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:latest
    networks:
      custommacvlan:
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    environment:
      - PUID=1001
      - PGID=1001
      - TZ='America/New York'
      - VERSION=docker
      - PLEX_CLAIM=
    volumes:
      - /appdata/plex_config:/config
      - /appdata/plex/anime:/tv
      - /appdata/plex/movies:/movies
      - /appdata/plex/music:/music
    devices:
      # This is to map onboard Intel UHD graphics (quick sync) to the container
      # Your requirements will be different if using a GPU for transcoding
      - /dev/dri:/dev/dri
    restart: unless-stopped
networks:
  custommacvlan:
    external: true
...