---
services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    network_mode: bridge
    ports:
      - "32400:32400/tcp"
    environment:
      - PUID=1001
      - PGID=1001
      - TZ='America/New York'
      - VERSION=docker
      - PLEX_CLAIM=
    volumes:
      - /appdata/plex_config:/config
      - /appdata/plex/anime:/tv
      - /appdata/plex/movies:/movies
      - /appdata/plex/music:/music
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
...