---
services:
  pihole:
    container_name: pihole-attached
    image: pihole/pihole:latest
    networks:
      exposed-macvlan:
        ipv4_address: 192.168.20.60
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: 'America/New York'
      WEBPASSWORD: 'pihole'
      FTLCONF_LOCAL_IPV4: 192.168.20.60
      DHCP_SERVER: false
      ServerIP: 192.168.20.60
      DHCP_ROUTER: 192.168.20.1
      DNSMASQ_LISTENING: local
      DNSSEC: true    
      PIHOLE_DNS_: 192.168.20.61
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
networks:
  exposed-macvlan:
    external: true
...